import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Link from 'next/link'
import Banner from '../components/Banner'
// https://agallaghermicha1-assessment1.vercel.app/
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Developers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="Next.js Dev" />
      <main className={styles.main}>

        <Banner title="Next.js Developers" tagline="We&apos;re always ready to build!" />


        {/* <h1 className={styles.title}>
          Next.js Developers
        </h1>
        <svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" fill="currentColor" class="bi bi-code-square" viewBox="0 0 16 16">
          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
          <path d="M6.854 4.646a.5.5 0 0 1 0 .708L4.207 8l2.647 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 0 1 .708 0zm2.292 0a.5.5 0 0 0 0 .708L11.793 8l-2.647 2.646a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708 0z"/>
        </svg>
        <p className={styles.description}>
          We&apos;re always ready to build!
        </p> */}
      </main>

      <footer className={styles.footer}>
        <Link href="/">Home</Link>
        <p>Azure Gallagher Michalak - For educational purposes</p>
      </footer>
    </div>
  )
}
