import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Link from 'next/link'
import Banner from '../components/Banner'
import LoginForm from '../components/LoginForm'
// https://agallaghermicha1-assessment1.vercel.app/
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="keywords" content="Next JS Developers Hire" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.PNG" />
      </Head>
      <Header title="Next.js Dev" />
      <main className={styles.main}>
        <LoginForm />
      </main>
      <footer className={styles.footer}>
        <Link href="/">Home</Link>
        <p>Azure Gallagher Michalak - For educational purposes</p>
      </footer>
    </div>
  )
}
